//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrayWolf.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrayWolf.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string About_Instructions {
            get {
                return ResourceManager.GetString("About_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Support.
        /// </summary>
        internal static string About_Support {
            get {
                return ResourceManager.GetString("About_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help/About.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string About_Web {
            get {
                return ResourceManager.GetString("About_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Photo/Video Caption Here....
        /// </summary>
        internal static string AddCaption_EditorPlaceholder {
            get {
                return ResourceManager.GetString("AddCaption_EditorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Caption.
        /// </summary>
        internal static string AddCaption_Title {
            get {
                return ResourceManager.GetString("AddCaption_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Event Note here... Event notes are time-stamped entries stored with logged data..
        /// </summary>
        internal static string AddEvent_LabelPlaceholder {
            get {
                return ResourceManager.GetString("AddEvent_LabelPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added event to &quot;{0}&quot;..
        /// </summary>
        internal static string AddEvent_SuccessMessage_Format {
            get {
                return ResourceManager.GetString("AddEvent_SuccessMessage_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string AddEvent_Title {
            get {
                return ResourceManager.GetString("AddEvent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Location Log File is selected. Please select a Location before attaching a video..
        /// </summary>
        internal static string AddVideo_SelectLoggerMessage {
            get {
                return ResourceManager.GetString("AddVideo_SelectLoggerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Location Log File contains photos and/or videos and may be too large to email. If you are emailing this file, you may reduce the size by deselecting images and videos. If you are saving the file to a cloud storage service like DropBox, Google Drive, OneDrive, etc., you can leave all images and videos selected and choose your destination on the subsequent screens..
        /// </summary>
        internal static string AttachmentsSizeWarning_Message {
            get {
                return ResourceManager.GetString("AttachmentsSizeWarning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AttachmentsSizeWarning_Title {
            get {
                return ResourceManager.GetString("AttachmentsSizeWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Details.
        /// </summary>
        internal static string BatteryStatus_Title {
            get {
                return ResourceManager.GetString("BatteryStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Caption.
        /// </summary>
        internal static string Button_AddCaption {
            get {
                return ResourceManager.GetString("Button_AddCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string Button_AddNote {
            get {
                return ResourceManager.GetString("Button_AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Button_Select {
            get {
                return ResourceManager.GetString("Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Log.
        /// </summary>
        internal static string Button_StopLog {
            get {
                return ResourceManager.GetString("Button_StopLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Chart_Day {
            get {
                return ResourceManager.GetString("Chart_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight hours.
        /// </summary>
        internal static string Chart_EightHours {
            get {
                return ResourceManager.GetString("Chart_EightHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        internal static string Chart_Everything {
            get {
                return ResourceManager.GetString("Chart_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifteen minutes.
        /// </summary>
        internal static string Chart_FifteenMinutes {
            get {
                return ResourceManager.GetString("Chart_FifteenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE GRAPH OF {0}.
        /// </summary>
        internal static string Chart_LiveGraph {
            get {
                return ResourceManager.GetString("Chart_LiveGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no data to display in {0}.
        /// </summary>
        internal static string Chart_NoDataToDisplay {
            get {
                return ResourceManager.GetString("Chart_NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One hour.
        /// </summary>
        internal static string Chart_OneHour {
            get {
                return ResourceManager.GetString("Chart_OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter:.
        /// </summary>
        internal static string Chart_Parameter {
            get {
                return ResourceManager.GetString("Chart_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEW GRAPH OF {0}.
        /// </summary>
        internal static string Chart_ReviewGraph {
            get {
                return ResourceManager.GetString("Chart_ReviewGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Location Log File is selected.
        /// </summary>
        internal static string Chart_SelectLocationMessage {
            get {
                return ResourceManager.GetString("Chart_SelectLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parameter.
        /// </summary>
        internal static string Chart_SelectParameter {
            get {
                return ResourceManager.GetString("Chart_SelectParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time option.
        /// </summary>
        internal static string Chart_SelectTimeOption {
            get {
                return ResourceManager.GetString("Chart_SelectTimeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time range:.
        /// </summary>
        internal static string Chart_TimeOption {
            get {
                return ResourceManager.GetString("Chart_TimeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to export this Location Log file?.
        /// </summary>
        internal static string Confirm_Export {
            get {
                return ResourceManager.GetString("Confirm_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to export and email this Location Log file?.
        /// </summary>
        internal static string Confirm_Export_Zip {
            get {
                return ResourceManager.GetString("Confirm_Export_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to display..
        /// </summary>
        internal static string Data_NoData {
            get {
                return ResourceManager.GetString("Data_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current set:.
        /// </summary>
        internal static string DataGrid_CurrentSet {
            get {
                return ResourceManager.GetString("DataGrid_CurrentSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data View is not available when logger is running.
        /// </summary>
        internal static string DataGrid_LoggerIsRunning {
            get {
                return ResourceManager.GetString("DataGrid_LoggerIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data View.
        /// </summary>
        internal static string DataGrid_Title {
            get {
                return ResourceManager.GetString("DataGrid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm custom password.
        /// </summary>
        internal static string DataSecurity_ConfirmPassword {
            get {
                return ResourceManager.GetString("DataSecurity_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        internal static string DataSecurity_IncludeCSV {
            get {
                return ResourceManager.GetString("DataSecurity_IncludeCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data files collected by WolfSense can be encrypted before exporting/emailing. To disable encryption select NO PASSWORD. To enable encryption, choose the default password or a custom password. For custom password, you must also enter it into WolfSense PC to open the file.
        ///
        ///Uncheck “Export CSV” if you do not want an unencrypted CSV file to be generated and sent with your data files..
        /// </summary>
        internal static string DataSecurity_InfoText {
            get {
                return ResourceManager.GetString("DataSecurity_InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string DataSecurity_InfoTitle {
            get {
                return ResourceManager.GetString("DataSecurity_InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        internal static string DataSecurity_PasswordMissmatch {
            get {
                return ResourceManager.GetString("DataSecurity_PasswordMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your interest in WolfSense Mobile, please enter your information below..
        /// </summary>
        internal static string DemoForm_Description {
            get {
                return ResourceManager.GetString("DemoForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string DemoForm_Email {
            get {
                return ResourceManager.GetString("DemoForm_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your name and email.
        /// </summary>
        internal static string DemoForm_EmptyDataMessage {
            get {
                return ResourceManager.GetString("DemoForm_EmptyDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DemoForm_Name {
            get {
                return ResourceManager.GetString("DemoForm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string DemoForm_Title {
            get {
                return ResourceManager.GetString("DemoForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle Counter.
        /// </summary>
        internal static string DeviceName_PC {
            get {
                return ResourceManager.GetString("DeviceName_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particulate Meter.
        /// </summary>
        internal static string DeviceName_PM {
            get {
                return ResourceManager.GetString("DeviceName_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WolfRadio.
        /// </summary>
        internal static string DeviceName_WR {
            get {
                return ResourceManager.GetString("DeviceName_WR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show me again.
        /// </summary>
        internal static string DoNotShowAgain {
            get {
                return ResourceManager.GetString("DoNotShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Location Log File is selected. Please select a Location Log File before capturing drawing note..
        /// </summary>
        internal static string DrawingNote_SelectLoggerMessage {
            get {
                return ResourceManager.GetString("DrawingNote_SelectLoggerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Log File.
        /// </summary>
        internal static string Email_LogFileMessageSubject {
            get {
                return ResourceManager.GetString("Email_LogFileMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attached .LCZ (Location Log File) was created in the WolfSense Mobile App. To open and view this file, use WolfSense PC which is available from GrayWolf Sensing Solutions at https://wolfsensepc.com/.
        /// </summary>
        internal static string Email_MessageBody {
            get {
                return ResourceManager.GetString("Email_MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrayWolf Logged Data.
        /// </summary>
        internal static string Email_MessageHeader {
            get {
                return ResourceManager.GetString("Email_MessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Probe Calibration.
        /// </summary>
        internal static string Error_CheckCal {
            get {
                return ResourceManager.GetString("Error_CheckCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Fault.
        /// </summary>
        internal static string Error_FanFault {
            get {
                return ResourceManager.GetString("Error_FanFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Error.
        /// </summary>
        internal static string Error_GeneralError {
            get {
                return ResourceManager.GetString("Error_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Sensor Error.
        /// </summary>
        internal static string Error_GeneralSensorError {
            get {
                return ResourceManager.GetString("Error_GeneralSensorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: High CO levels (&gt;10ppm) will influence Formaldehyde readings..
        /// </summary>
        internal static string Error_HCHO_HiCO {
            get {
                return ResourceManager.GetString("Error_HCHO_HiCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low levels of %RH (&lt;20% RH) will negatively impact HCHO Readings. This sensor is NOT recommended for use in environments with &lt;20 %RH..
        /// </summary>
        internal static string Error_HCHO_LoRH {
            get {
                return ResourceManager.GetString("Error_HCHO_LoRH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CO sensor – cannot display HCHO cross-sensitivity messages..
        /// </summary>
        internal static string Error_HCHO_NoCO {
            get {
                return ResourceManager.GetString("Error_HCHO_NoCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Temperature/RH Sensor.
        /// </summary>
        internal static string Error_MissingTRH {
            get {
                return ResourceManager.GetString("Error_MissingTRH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is required.
        /// </summary>
        internal static string Error_NetworkRequired {
            get {
                return ResourceManager.GetString("Error_NetworkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sensors Installed.
        /// </summary>
        internal static string Error_NoSensorsInstalled {
            get {
                return ResourceManager.GetString("Error_NoSensorsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe battery critical.
        /// </summary>
        internal static string Error_ProbeBatteryCritical {
            get {
                return ResourceManager.GetString("Error_ProbeBatteryCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi is disconnected.
        /// </summary>
        internal static string Error_WiFi_Disco {
            get {
                return ResourceManager.GetString("Error_WiFi_Disco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to file successful..
        /// </summary>
        internal static string Export_Success {
            get {
                return ResourceManager.GetString("Export_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string GalleryAttachmentsSettings_Disabled {
            get {
                return ResourceManager.GetString("GalleryAttachmentsSettings_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string GalleryAttachmentsSettings_Enabled {
            get {
                return ResourceManager.GetString("GalleryAttachmentsSettings_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Photos/Video from Gallery.
        /// </summary>
        internal static string GalleryAttachmentsSettings_Title {
            get {
                return ResourceManager.GetString("GalleryAttachmentsSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here to select GrayWolf devices..
        /// </summary>
        internal static string HomePage_EmptyListMessage {
            get {
                return ResourceManager.GetString("HomePage_EmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Log File: {0}.
        /// </summary>
        internal static string HomePage_LocationFormat {
            get {
                return ResourceManager.GetString("HomePage_LocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TAP TO SELECT LOCATION LOG FILE&gt;.
        /// </summary>
        internal static string HomePage_SelectLocation {
            get {
                return ResourceManager.GetString("HomePage_SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE IN DEMO MODE.
        /// </summary>
        internal static string HomePage_UseInDemoMode {
            get {
                return ResourceManager.GetString("HomePage_UseInDemoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source:.
        /// </summary>
        internal static string Localization_SelectPhotoSource {
            get {
                return ResourceManager.GetString("Localization_SelectPhotoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        internal static string Locations_Add {
            get {
                return ResourceManager.GetString("Locations_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Locations_AreYouSure {
            get {
                return ResourceManager.GetString("Locations_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear this Location Log File?.
        /// </summary>
        internal static string Locations_ClearConfirmationText {
            get {
                return ResourceManager.GetString("Locations_ClearConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Location Log File?.
        /// </summary>
        internal static string Locations_DeleteConfirmationText {
            get {
                return ResourceManager.GetString("Locations_DeleteConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or create a data file below..
        /// </summary>
        internal static string Locations_Hint {
            get {
                return ResourceManager.GetString("Locations_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Log Files:.
        /// </summary>
        internal static string Locations_Locations {
            get {
                return ResourceManager.GetString("Locations_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Locations_Share {
            get {
                return ResourceManager.GetString("Locations_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Log Files.
        /// </summary>
        internal static string Locations_Title {
            get {
                return ResourceManager.GetString("Locations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the file name:.
        /// </summary>
        internal static string Log_EnterFileName {
            get {
                return ResourceManager.GetString("Log_EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid file name..
        /// </summary>
        internal static string Log_EnterValidFileName {
            get {
                return ResourceManager.GetString("Log_EnterValidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events can only be logged while logger is running..
        /// </summary>
        internal static string Log_Events_NotRunningMessage {
            get {
                return ResourceManager.GetString("Log_Events_NotRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Log File name should be less than {0} characters..
        /// </summary>
        internal static string Log_FileNameTooLongFormat {
            get {
                return ResourceManager.GetString("Log_FileNameTooLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Location Log File with that name already exists!.
        /// </summary>
        internal static string Log_LocationAlreadyExist {
            get {
                return ResourceManager.GetString("Log_LocationAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone is not available.
        /// </summary>
        internal static string Log_RecordDeviceNotAvailable {
            get {
                return ResourceManager.GetString("Log_RecordDeviceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not change locations while logger is running.
        /// </summary>
        internal static string Log_SelectionWhileLoggingMessage {
            get {
                return ResourceManager.GetString("Log_SelectionWhileLoggingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap shot log recorded to &quot;{0}&quot;.
        /// </summary>
        internal static string Log_SnapshotCreated_Format {
            get {
                return ResourceManager.GetString("Log_SnapshotCreated_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was logged.
        /// </summary>
        internal static string Log_SnapshotNotCreated {
            get {
                return ResourceManager.GetString("Log_SnapshotNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage permissions required to attach documents.
        /// </summary>
        internal static string Log_StoragePermissionsMessage {
            get {
                return ResourceManager.GetString("Log_StoragePermissionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPEND.
        /// </summary>
        internal static string LogFileWritingMode_Append {
            get {
                return ResourceManager.GetString("LogFileWritingMode_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERWRITE.
        /// </summary>
        internal static string LogFileWritingMode_Overwrite {
            get {
                return ResourceManager.GetString("LogFileWritingMode_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not export, share or delete Location Log Files while the logger is running..
        /// </summary>
        internal static string Logger_NotWhileLogging {
            get {
                return ResourceManager.GetString("Logger_NotWhileLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in (GrayWolfLive Account Required).
        /// </summary>
        internal static string Login_AccountRequired {
            get {
                return ResourceManager.GetString("Login_AccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Login_ButtonText {
            get {
                return ResourceManager.GetString("Login_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Text Note Here... Text note will be stored with logged data..
        /// </summary>
        internal static string LogNote_EditorPlaceholder {
            get {
                return ResourceManager.GetString("LogNote_EditorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Note.
        /// </summary>
        internal static string LogNote_Title {
            get {
                return ResourceManager.GetString("LogNote_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera permission denied. Go to Settings and Enable Camera Permission to allow WolfSense to attach photos to your Location Log Files..
        /// </summary>
        internal static string LogService_CameraPermissionsDenied {
            get {
                return ResourceManager.GetString("LogService_CameraPermissionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string LogService_CameraSource {
            get {
                return ResourceManager.GetString("LogService_CameraSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gallery available.
        /// </summary>
        internal static string LogService_GalleryIsNotAvailable {
            get {
                return ResourceManager.GetString("LogService_GalleryIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string LogService_GallerySource {
            get {
                return ResourceManager.GetString("LogService_GallerySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Select Option:.
        /// </summary>
        internal static string LogService_LogAlreadyExistMessage {
            get {
                return ResourceManager.GetString("LogService_LogAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Stopped..
        /// </summary>
        internal static string LogService_LoggingStopped {
            get {
                return ResourceManager.GetString("LogService_LoggingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media file logged successfully..
        /// </summary>
        internal static string LogService_MediaFileLogged {
            get {
                return ResourceManager.GetString("LogService_MediaFileLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera available..
        /// </summary>
        internal static string LogService_NoCameraAvailableMessage {
            get {
                return ResourceManager.GetString("LogService_NoCameraAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        internal static string LogService_OverwriteButton {
            get {
                return ResourceManager.GetString("LogService_OverwriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite current Log Location File?.
        /// </summary>
        internal static string LogService_OverwriteDialogTitle {
            get {
                return ResourceManager.GetString("LogService_OverwriteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Log Location File is selected. Please select a Location Log File before adding a note..
        /// </summary>
        internal static string LogService_SelectLocationBeforeNote {
            get {
                return ResourceManager.GetString("LogService_SelectLocationBeforeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Log Location file is selected. Please select a Location Log File before attaching a photo.
        /// </summary>
        internal static string LogService_SelectLocationBeforePhoto {
            get {
                return ResourceManager.GetString("LogService_SelectLocationBeforePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Log Location File is selected. Please select a Location Log File before recording..
        /// </summary>
        internal static string LogService_SelectLocationBeforeRecord {
            get {
                return ResourceManager.GetString("LogService_SelectLocationBeforeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video file logged successfully..
        /// </summary>
        internal static string LogService_VideoFileLogged {
            get {
                return ResourceManager.GetString("LogService_VideoFileLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help/About.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo mode is already started.
        /// </summary>
        internal static string Menu_AlreadyInDemo {
            get {
                return ResourceManager.GetString("Menu_AlreadyInDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo mode is already stopped.
        /// </summary>
        internal static string Menu_AlreadyStoppedDemo {
            get {
                return ResourceManager.GetString("Menu_AlreadyStoppedDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string Menu_Audio {
            get {
                return ResourceManager.GetString("Menu_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close App.
        /// </summary>
        internal static string Menu_CloseApp {
            get {
                return ResourceManager.GetString("Menu_CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Menu_Data {
            get {
                return ResourceManager.GetString("Menu_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        internal static string Menu_Drawing {
            get {
                return ResourceManager.GetString("Menu_Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data file security.
        /// </summary>
        internal static string Menu_Encryption {
            get {
                return ResourceManager.GetString("Menu_Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End demo mode.
        /// </summary>
        internal static string Menu_EndDemo {
            get {
                return ResourceManager.GetString("Menu_EndDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Menu_Event {
            get {
                return ResourceManager.GetString("Menu_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera/Video.
        /// </summary>
        internal static string Menu_GalleryAttachmentsSettings {
            get {
                return ResourceManager.GetString("Menu_GalleryAttachmentsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        internal static string Menu_Graph {
            get {
                return ResourceManager.GetString("Menu_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string Menu_Live {
            get {
                return ResourceManager.GetString("Menu_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string Menu_Locations {
            get {
                return ResourceManager.GetString("Menu_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Menu_Log {
            get {
                return ResourceManager.GetString("Menu_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Menu_Notes {
            get {
                return ResourceManager.GetString("Menu_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter names.
        /// </summary>
        internal static string Menu_ParameterNames {
            get {
                return ResourceManager.GetString("Menu_ParameterNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Menu_Photo {
            get {
                return ResourceManager.GetString("Menu_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Options.
        /// </summary>
        internal static string Menu_ProbeOptions {
            get {
                return ResourceManager.GetString("Menu_ProbeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readings.
        /// </summary>
        internal static string Menu_Readings {
            get {
                return ResourceManager.GetString("Menu_Readings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Notes.
        /// </summary>
        internal static string Menu_ReviewNotes {
            get {
                return ResourceManager.GetString("Menu_ReviewNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Devices.
        /// </summary>
        internal static string Menu_SelectDevices {
            get {
                return ResourceManager.GetString("Menu_SelectDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start IAQ demo mode.
        /// </summary>
        internal static string Menu_StartDemoIAQ {
            get {
                return ResourceManager.GetString("Menu_StartDemoIAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start TOX demo mode.
        /// </summary>
        internal static string Menu_StartDemoTOX {
            get {
                return ResourceManager.GetString("Menu_StartDemoTOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Log.
        /// </summary>
        internal static string Menu_StartLog {
            get {
                return ResourceManager.GetString("Menu_StartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Log.
        /// </summary>
        internal static string Menu_StopLog {
            get {
                return ResourceManager.GetString("Menu_StopLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Note.
        /// </summary>
        internal static string Menu_Text {
            get {
                return ResourceManager.GetString("Menu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Menu_Video {
            get {
                return ResourceManager.GetString("Menu_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Help.
        /// </summary>
        internal static string Menu_VideoHelp {
            get {
                return ResourceManager.GetString("Menu_VideoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOC.
        /// </summary>
        internal static string Menu_VOC {
            get {
                return ResourceManager.GetString("Menu_VOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was cancelled..
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Long Parameter Names.
        /// </summary>
        internal static string ParameterNames_UseLong {
            get {
                return ResourceManager.GetString("ParameterNames_UseLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Short Parameter Names.
        /// </summary>
        internal static string ParameterNames_UseShort {
            get {
                return ResourceManager.GetString("ParameterNames_UseShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom password.
        /// </summary>
        internal static string Password_CustomPassword {
            get {
                return ResourceManager.GetString("Password_CustomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default password.
        /// </summary>
        internal static string Password_DefaultPassword {
            get {
                return ResourceManager.GetString("Password_DefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password.
        /// </summary>
        internal static string Password_NoEncryption {
            get {
                return ResourceManager.GetString("Password_NoEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Security.
        /// </summary>
        internal static string Password_Title {
            get {
                return ResourceManager.GetString("Password_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain 8-30 characters, including 1 lowercase, 1 uppercase, 1 digit and 1 special character and must not contain whitespaces.
        /// </summary>
        internal static string Password_ValidationRulesMessage {
            get {
                return ResourceManager.GetString("Password_ValidationRulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not supported on this platform..
        /// </summary>
        internal static string Platform_NotSupported {
            get {
                return ResourceManager.GetString("Platform_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Level:.
        /// </summary>
        internal static string Probe_BatteryLevel {
            get {
                return ResourceManager.GetString("Probe_BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device has disconnected. Please select MENU/ READINGS/ SELECT DEVICES to re-connect..
        /// </summary>
        internal static string Probe_DisconnectMsg {
            get {
                return ResourceManager.GetString("Probe_DisconnectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline / Disconnected.
        /// </summary>
        internal static string Probe_Offline {
            get {
                return ResourceManager.GetString("Probe_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Status:.
        /// </summary>
        internal static string Probe_ProbeStatus {
            get {
                return ResourceManager.GetString("Probe_ProbeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        internal static string Probe_Sensors {
            get {
                return ResourceManager.GetString("Probe_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number: .
        /// </summary>
        internal static string Probe_SerialNumber {
            get {
                return ResourceManager.GetString("Probe_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Status.
        /// </summary>
        internal static string Probe_Title {
            get {
                return ResourceManager.GetString("Probe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Power On Time:.
        /// </summary>
        internal static string Probe_UpTime {
            get {
                return ResourceManager.GetString("Probe_UpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Snapshot Log from DSII Log Button.
        /// </summary>
        internal static string ProbeOptions_EnableSnapshotButtonFromDSIIDevice {
            get {
                return ResourceManager.GetString("ProbeOptions_EnableSnapshotButtonFromDSIIDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Options.
        /// </summary>
        internal static string ProbeOptions_Title {
            get {
                return ResourceManager.GetString("ProbeOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio note stored..
        /// </summary>
        internal static string RecordSound_AttachmentAdded {
            get {
                return ResourceManager.GetString("RecordSound_AttachmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted audio note..
        /// </summary>
        internal static string RecordSound_AttachmentsDeleted {
            get {
                return ResourceManager.GetString("RecordSound_AttachmentsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string RecordSound_Delete {
            get {
                return ResourceManager.GetString("RecordSound_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string RecordSound_Play {
            get {
                return ResourceManager.GetString("RecordSound_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string RecordSound_Record {
            get {
                return ResourceManager.GetString("RecordSound_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string RecordSound_Stop {
            get {
                return ResourceManager.GetString("RecordSound_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Note.
        /// </summary>
        internal static string RecordSound_Title {
            get {
                return ResourceManager.GetString("RecordSound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Photos.
        /// </summary>
        internal static string ReviewPhotos_Title {
            get {
                return ResourceManager.GetString("ReviewPhotos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Videos.
        /// </summary>
        internal static string ReviewVideos_Title {
            get {
                return ResourceManager.GetString("ReviewVideos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string Select_Language {
            get {
                return ResourceManager.GetString("Select_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Location Log File contains photos and videos and may be too large if you are using email. Deselect images and videos to reduce the size..
        /// </summary>
        internal static string SelectAttachmentFiles_Description {
            get {
                return ResourceManager.GetString("SelectAttachmentFiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        internal static string SelectAttachmentFiles_Files {
            get {
                return ResourceManager.GetString("SelectAttachmentFiles_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Photos/Videos to include.
        /// </summary>
        internal static string SelectAttachmentFiles_Title {
            get {
                return ResourceManager.GetString("SelectAttachmentFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth devices:.
        /// </summary>
        internal static string SelectDevices_Bluetooth {
            get {
                return ResourceManager.GetString("SelectDevices_Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SelectDevices_Cancel {
            get {
                return ResourceManager.GetString("SelectDevices_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes are not allowed in demo mode..
        /// </summary>
        internal static string SelectDevices_CannotOpenInDemo {
            get {
                return ResourceManager.GetString("SelectDevices_CannotOpenInDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud devices:.
        /// </summary>
        internal static string SelectDevices_Cloud {
            get {
                return ResourceManager.GetString("SelectDevices_Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrayWolfLive Cloud:.
        /// </summary>
        internal static string SelectDevices_CloudTitle {
            get {
                return ResourceManager.GetString("SelectDevices_CloudTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        internal static string SelectDevices_LoggedInAs {
            get {
                return ResourceManager.GetString("SelectDevices_LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In to GrayWolfLive.
        /// </summary>
        internal static string SelectDevices_LogIn {
            get {
                return ResourceManager.GetString("SelectDevices_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes are not allowed while logger is running..
        /// </summary>
        internal static string SelectDevices_LogIsRunningMessage {
            get {
                return ResourceManager.GetString("SelectDevices_LogIsRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string SelectDevices_LogOut {
            get {
                return ResourceManager.GetString("SelectDevices_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        internal static string SelectDevices_NotLoggedIn {
            get {
                return ResourceManager.GetString("SelectDevices_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SelectDevices_Ok {
            get {
                return ResourceManager.GetString("SelectDevices_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select devices:.
        /// </summary>
        internal static string SelectDevices_Select {
            get {
                return ResourceManager.GetString("SelectDevices_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select devices.
        /// </summary>
        internal static string SelectDevices_Title {
            get {
                return ResourceManager.GetString("SelectDevices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Location Log Files to display..
        /// </summary>
        internal static string SelectFileForDataGrid_NoItemsMessage {
            get {
                return ResourceManager.GetString("SelectFileForDataGrid_NoItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location Log File.
        /// </summary>
        internal static string SelectFileForDataGrid_Title {
            get {
                return ResourceManager.GetString("SelectFileForDataGrid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Option.
        /// </summary>
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sensor Tip.
        /// </summary>
        internal static string SelectSensorTip_Title {
            get {
                return ResourceManager.GetString("SelectSensorTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select set.
        /// </summary>
        internal static string SelectSet_Title {
            get {
                return ResourceManager.GetString("SelectSet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select VOC Item.
        /// </summary>
        internal static string SelectVOCItem_Title {
            get {
                return ResourceManager.GetString("SelectVOCItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Unit.
        /// </summary>
        internal static string SensorPopup_Confirm {
            get {
                return ResourceManager.GetString("SensorPopup_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display on home page.
        /// </summary>
        internal static string SensorPopup_DisplayedInUI {
            get {
                return ResourceManager.GetString("SensorPopup_DisplayedInUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string SensorPopup_IsLogged {
            get {
                return ResourceManager.GetString("SensorPopup_IsLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        internal static string SensorPopup_SerialNum {
            get {
                return ResourceManager.GetString("SensorPopup_SerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips &gt;&gt;&gt;.
        /// </summary>
        internal static string SensorPopup_Tips {
            get {
                return ResourceManager.GetString("SensorPopup_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string SensorPopup_Title {
            get {
                return ResourceManager.GetString("SensorPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string SensorPopup_Unit {
            get {
                return ResourceManager.GetString("SensorPopup_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Units.
        /// </summary>
        internal static string SensorPopup_Units {
            get {
                return ResourceManager.GetString("SensorPopup_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOC &gt;&gt;&gt;.
        /// </summary>
        internal static string SensorPopup_VOC {
            get {
                return ResourceManager.GetString("SensorPopup_VOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Sensors require a stabilization period of 5 minutes when first powered on before use. During stabilization, Snap Shot log is disabled and Trend Log storage is deferred. When sensors are fully stabilized, the sensor icon will disappear, the readings color will be black, and all log functions will be restored..
        /// </summary>
        internal static string SensorStabilization_Generic {
            get {
                return ResourceManager.GetString("SensorStabilization_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PID sensor requires a MINIMUM of 15 minutes stabilization if the sensor has been used recently, and 30 minutes if the sensor is used on a frequent basis.  A 24-hour stabilization period is recommended if the sensor has been stored for a significant amount of time, exposed to high humidity or sources of contamination, or prior to user-calibration. Please refer to Sensor Tips and PID Guides for more information..
        /// </summary>
        internal static string SensorStabilization_PID {
            get {
                return ResourceManager.GetString("SensorStabilization_PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Status Error.
        /// </summary>
        internal static string SensorStatusError_Title {
            get {
                return ResourceManager.GetString("SensorStatusError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Basics For.
        /// </summary>
        internal static string SensorTip_DefaultText {
            get {
                return ResourceManager.GetString("SensorTip_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Tip &gt;&gt;&gt;.
        /// </summary>
        internal static string SensorTips_ChangeTip {
            get {
                return ResourceManager.GetString("SensorTips_ChangeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Tip.
        /// </summary>
        internal static string SensorTips_SensorTip {
            get {
                return ResourceManager.GetString("SensorTips_SensorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Tips.
        /// </summary>
        internal static string SensorTips_Title {
            get {
                return ResourceManager.GetString("SensorTips_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attached .LCZ (Location Log File) was created in the WolfSense Mobile App. To open and view this file, use WolfSense PC which is available from GrayWolf Sensing Solutions at https://wolfsensepc.com/.
        /// </summary>
        internal static string Share_InstructionsFileText {
            get {
                return ResourceManager.GetString("Share_InstructionsFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Image.
        /// </summary>
        internal static string ShowImage_Title {
            get {
                return ResourceManager.GetString("ShowImage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Video.
        /// </summary>
        internal static string ShowVideo_Title {
            get {
                return ResourceManager.GetString("ShowVideo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Log Location File.
        /// </summary>
        internal static string StartLog_AddLocation {
            get {
                return ResourceManager.GetString("StartLog_AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on Add button to add new Location Log File..
        /// </summary>
        internal static string StartLog_EmptyLocationsMessage {
            get {
                return ResourceManager.GetString("StartLog_EmptyLocationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval :.
        /// </summary>
        internal static string StartLog_Interval {
            get {
                return ResourceManager.GetString("StartLog_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select devices using READINGS/ SELECT DEVICES.
        /// </summary>
        internal static string StartLog_SelectDevicesMessage {
            get {
                return ResourceManager.GetString("StartLog_SelectDevicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location Log File:.
        /// </summary>
        internal static string StartLog_SelectLocation {
            get {
                return ResourceManager.GetString("StartLog_SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Location Log File..
        /// </summary>
        internal static string StartLog_SelectLocationMessage {
            get {
                return ResourceManager.GetString("StartLog_SelectLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots may not be taken while Trend Log is running..
        /// </summary>
        internal static string StartLog_Snahshot_LogIsAlreadyRunning {
            get {
                return ResourceManager.GetString("StartLog_Snahshot_LogIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        internal static string StartLog_Snapshot {
            get {
                return ResourceManager.GetString("StartLog_Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Log.
        /// </summary>
        internal static string StartLog_TrendingLog {
            get {
                return ResourceManager.GetString("StartLog_TrendingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend Log.
        /// </summary>
        internal static string Title_TrendLog {
            get {
                return ResourceManager.GetString("Title_TrendLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging to {0} at interval {1} seconds.
        /// </summary>
        internal static string TrendLog_Status {
            get {
                return ResourceManager.GetString("TrendLog_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Name(s).
        /// </summary>
        internal static string VOCList_AltName {
            get {
                return ResourceManager.GetString("VOCList_AltName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Correction Factor.
        /// </summary>
        internal static string VOCList_CorrectionFactor {
            get {
                return ResourceManager.GetString("VOCList_CorrectionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Formula.
        /// </summary>
        internal static string VOCList_Formula {
            get {
                return ResourceManager.GetString("VOCList_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSHA PEL.
        /// </summary>
        internal static string VOCList_OSHAPel {
            get {
                return ResourceManager.GetString("VOCList_OSHAPel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name of compound.
        /// </summary>
        internal static string VOCList_SearchPlaceholder {
            get {
                return ResourceManager.GetString("VOCList_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOC.
        /// </summary>
        internal static string VOCList_Title {
            get {
                return ResourceManager.GetString("VOCList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOC Item.
        /// </summary>
        internal static string VOCList_VOCItem {
            get {
                return ResourceManager.GetString("VOCList_VOCItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to WolfSense Mobile. This app requires a DirectSense II Smart Probe (or 2, up to 3) connected via Bluetooth to function. Simulated readings can be accessed to evaluate the app by selecting MAIN MENU &gt; READINGS &gt; START DEMO MODE..
        /// </summary>
        internal static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WolfSense - Alert.
        /// </summary>
        internal static string WolfSenseAlert_Title {
            get {
                return ResourceManager.GetString("WolfSenseAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WolfSense.
        /// </summary>
        internal static string WolfSenseMessage_Title {
            get {
                return ResourceManager.GetString("WolfSenseMessage_Title", resourceCulture);
            }
        }
    }
}
